from app import db
from app.models.cerveza import Cerveza

def agregar_cervezas():
    cerveza1 = Cerveza(nombre='Dark Lager', marca='Principia',porcentaje_alcohol=4.0, estilo='lager', ibus=22, color='obscura', sabor='Caramelo y tostado', ingrediente_adicional='cafe')
    cerveza2 = Cerveza(nombre='American Wheat Ale', marca='Principia',porcentaje_alcohol=4.3, estilo='wheat ale', ibus=18, color='clara', sabor='ligero y refrescante', ingrediente_adicional='ninguno')
    cerveza3 = Cerveza(nombre='Extrasolar', marca='Principia',porcentaje_alcohol=6.5, estilo='ipa', ibus=30, color='clara turbia', sabor='frutal y dulce', ingrediente_adicional='frutas')
    cerveza4 = Cerveza(nombre='Spectra', marca='Principia',porcentaje_alcohol=6.7, estilo='ipa', ibus=60, color='clara dorada', sabor='citrico', ingrediente_adicional='ninguno')
    cerveza5 = Cerveza(nombre='Asimetria', marca='Principia',porcentaje_alcohol=5.5, estilo='stout', ibus=20, color='obscura', sabor=['caramelo','tostado'], ingrediente_adicional='mantequilla de mani')
    cerveza6 = Cerveza(nombre='Craft Pilsner', marca='Principia',porcentaje_alcohol=4.1, estilo='pilsner', ibus=27, color='clara', sabor='citrico', ingrediente_adicional='frutas')
    cerveza7 = Cerveza(nombre='Lunada', marca='De la Costa',porcentaje_alcohol=5.0, estilo='dunkel', ibus=23, color='obscura', sabor='tostado', ingrediente_adicional='chocolate')
    cerveza8 = Cerveza(nombre='Bahia', marca='De la Costa',porcentaje_alcohol=3.8, estilo='lager', ibus=14, color='muy clara', sabor='ligero y refrescante', ingrediente_adicional='ninguno')
    cerveza9 = Cerveza(nombre='Harry Polanco', marca='Wendlandt',porcentaje_alcohol=5.5, estilo='red ale', ibus=50, color='rojiza', sabor=['caramelo','tostado'], ingrediente_adicional='ninguno')
    cerveza10 = Cerveza(nombre='Perro del mar', marca='Wendlandt',porcentaje_alcohol=7.0, estilo='ipa', ibus=60, color='clara', sabor='amargo intenso', ingrediente_adicional='ninguno')
    cerveza11 = Cerveza(nombre='Foca parlante', marca='Wendlandt',porcentaje_alcohol=5.5, estilo='stout', ibus=38, color='obscura', sabor='tostado', ingrediente_adicional=['cafe','chocolate'])
    cerveza12 = Cerveza(nombre='Vaquita marina', marca='Wendlandt',porcentaje_alcohol=5.2, estilo='pale ale', ibus=42, color='clara', sabor='citrico', ingrediente_adicional='ninguno')
    cerveza13 = Cerveza(nombre='Veraniega', marca='Wendlandt',porcentaje_alcohol=4.7, estilo='pale ale', ibus=20, color='muy clara', sabor='ligero y refrescante', ingrediente_adicional='ninguno')
    cerveza14 = Cerveza(nombre='Frambuesa', marca='Stiegl',porcentaje_alcohol=2.0, estilo='lager frutal', ibus=8, color='clara', sabor='frutal y dulce', ingrediente_adicional='frutas')
    cerveza15 = Cerveza(nombre='Toronja',marca='Stiegl',porcentaje_alcohol=2.0, estilo='lager frutal', ibus=8, color='clara', sabor='frutal y dulce', ingrediente_adicional='frutas')
    cerveza16 = Cerveza(nombre='Limon', marca='Stiegl',porcentaje_alcohol=2.0, estilo='lager frutal', ibus=8, color='clara', sabor='ligero y refrescante', ingrediente_adicional='frutas')
    cerveza17 = Cerveza(nombre='Lagrimas negras', marca='Ramuri',porcentaje_alcohol=10.0, estilo='imperial cacao stout', ibus=34, color='muy obscura', sabor='tostado', ingrediente_adicional='chocolate')
    cerveza18 = Cerveza(nombre='Lagrimas de cacahuate', marca='Ramuri',porcentaje_alcohol=8.0, estilo='imperial cacao stout', ibus=38, color='muy obscura', sabor='ninguno', ingrediente_adicional='mantequilla de mani')
    cerveza19 = Cerveza(nombre='Odin', marca='Ramuri', porcentaje_alcohol=9.3, estilo='imperial coffee stout', ibus=74, color='muy obscura', sabor='ninguno', ingrediente_adicional='cafe')
    cerveza20 = Cerveza(nombre='Estrella Galicia', marca='Estrella de Galicia',porcentaje_alcohol=5.5, estilo='helles export bierr',ibus=25, color='dorado', sabor='ligero y refrescante', ingrediente_adicional='ninguno')
    cerveza21 = Cerveza(nombre='Spring IPA', marca='19 Norte',porcentaje_alcohol=7.5, estilo='ipa', ibus=60, color='clara', sabor='caramelo', ingrediente_adicional='ninguno')
    cerveza22 = Cerveza(nombre='Dakota Stout', marca='19 Norte',porcentaje_alcohol=7.8, estilo='stout', ibus=40, color='obscura', sabor='ninguno', ingrediente_adicional=['cafe','chocolate'])
    cerveza23 = Cerveza(nombre='Summer Daze', marca='19 Norte',porcentaje_alcohol=6, estilo='wheat ale', ibus=29, color='clara', sabor='citrico', ingrediente_adicional='frutas')
    cerveza24 = Cerveza(nombre='Latin Lager', marca='19 Norte',porcentaje_alcohol=5.5, estilo='lager', ibus=40, color='clara', sabor='ligero y refrescante', ingrediente_adicional='ninguno')
    cerveza25 = Cerveza(nombre='Caramelo Brown', marca='19 Norte',porcentaje_alcohol=7.6, estilo='brown ale', ibus=22, color='caramelo', sabor='caramelo', ingrediente_adicional='chocolate')
    cerveza26 = Cerveza(nombre='Porter', marca='Xinampa',porcentaje_alcohol=6, estilo='porter', ibus=45, color='obscura', sabor='tostado', ingrediente_adicional='ninguno')
    cerveza27 = Cerveza(nombre='Amber Ale', marca='Xinampa',porcentaje_alcohol=5.5, estilo='amber ale', ibus=40, color='clara', sabor=['caramelo','citrico'], ingrediente_adicional='ninguno')
    cerveza28 = Cerveza(nombre='Pale Ale', marca='Xinampa',porcentaje_alcohol=5.5, estilo='pale ale', ibus=40, color='clara', sabor='ninguno', ingrediente_adicional='ninguno')

    db.session.add(cerveza1)
    db.session.add(cerveza2)
    db.session.add(cerveza3)
    db.session.add(cerveza4)
    db.session.add(cerveza5)
    db.session.add(cerveza6)
    db.session.add(cerveza7)
    db.session.add(cerveza8)
    db.session.add(cerveza9)
    db.session.add(cerveza10)
    db.session.add(cerveza11)
    db.session.add(cerveza12)
    db.session.add(cerveza13)
    db.session.add(cerveza14)
    db.session.add(cerveza15)
    db.session.add(cerveza16)
    db.session.add(cerveza17)
    db.session.add(cerveza18)
    db.session.add(cerveza19)
    db.session.add(cerveza20)
    db.session.add(cerveza21)
    db.session.add(cerveza22)
    db.session.add(cerveza23)
    db.session.add(cerveza24)
    db.session.add(cerveza25)
    db.session.add(cerveza26)
    db.session.add(cerveza27)
    db.session.add(cerveza28)

    db.session.commit()

if __name__ == "__main__":
    from app import create_app

    app = create_app()
    with app.app_context():
        agregar_cervezas()