"""empty message

Revision ID: 416779116735
Revises: 0eda63f2d7b6
Create Date: 2023-07-14 17:53:24.754900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416779116735'
down_revision = '0eda63f2d7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encuesta', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encuesta', 'completed_at')
    # ### end Alembic commands ###
