"""empty message

Revision ID: 64674f3014de
Revises: 
Create Date: 2023-07-14 17:24:02.865322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64674f3014de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cerveza',
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('porcentaje_alcohol', sa.Integer(), nullable=True),
    sa.Column('estilo', sa.String(), nullable=True),
    sa.Column('ibus', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sabor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cerveza_id')
    )
    op.create_table('cliente',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('encuesta',
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.Column('consumo_previo', sa.Boolean(), nullable=True),
    sa.Column('pref_estilo', sa.String(), nullable=True),
    sa.Column('gusta_amarga', sa.Boolean(), nullable=True),
    sa.Column('pref_sabor', sa.String(), nullable=True),
    sa.Column('pref_alcohol', sa.Integer(), nullable=True),
    sa.Column('ingrediente_adic', sa.String(), nullable=True),
    sa.Column('cerveza_recomendada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_recomendada_id'], ['cerveza.cerveza_id'], ),
    sa.PrimaryKeyConstraint('encuesta_id')
    )
    op.create_table('favoritos',
    sa.Column('favoritos_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cerveza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cerveza.cerveza_id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('favoritos_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('encuesta')
    op.drop_table('cliente')
    op.drop_table('cerveza')
    # ### end Alembic commands ###
