"""empty message

Revision ID: d215aa01489b
Revises: c88ad1967ab7
Create Date: 2023-08-12 14:05:55.954311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd215aa01489b'
down_revision = 'c88ad1967ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    op.drop_constraint('encuesta_cliente_id_fkey', 'encuesta', type_='foreignkey')
    op.drop_constraint('favoritos_cliente_id_fkey', 'favoritos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favoritos_cliente_id_fkey', 'favoritos', 'cliente', ['cliente_id'], ['cliente_id'])
    op.create_foreign_key('encuesta_cliente_id_fkey', 'encuesta', 'cliente', ['cliente_id'], ['cliente_id'])
    op.create_table('cliente',
    sa.Column('cliente_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cliente_id', name='cliente_pkey')
    )
    # ### end Alembic commands ###
